#!/usr/bin/perl

use strict;
use warnings;

my $total;
while (<>) {
    my ($o, $r) = split;
    $o =~ tr/ABC/123/;
    $r =~ tr/XYZ/123/;
    $total += $r + (($r == $o) ? 3 : ($r == (($o % 3) + 1)) ? 6 : 0);
}
print "$total\n";
